In [1]:
from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([[1], [2], [3], [4], [5]])  # must be 2D
y = np.array([2, 4, 5, 4, 5])

model = LinearRegression() # empty object initialized
model.fit(X, y) # formula-> it solves the xtx 

model.predict([[6]])

array([5.8])

In [2]:
model.coef_

array([0.6])

In [3]:
model.intercept_

np.float64(2.2)

In [4]:
m = model.coef_
b = model.intercept_
m * 6 + b

array([5.8])